us-169 Login Seite gestalten
solid-stack-solutions/voycar-frontend pull request #12
Opened 2024-06-21 15:29 UTC by Janniix

[User story 169](https://tree.taiga.io/project/julius-boettger-voycar/us/169)
Design der Login Seite ist fertig, Logik wird dann in [us 170](https://tree.taiga.io/project/julius-boettger-voycar/us/170) implementiert

2024-06-21 15:37 UTC, Janniix commented
Gerade closed, weil noch der Indikator bei falscher Eingabe ergänzt werden muss. Wird gereopened sobald der drin ist

2024-06-21 15:49 UTC, Janniix commented
Indikatoren wurden ergänzt

2024-06-21 16:21 UTC, julius-boettger requested changes
Nice-to-haves wären noch...
- Ein "Passwort sichtbar machen" Knopf
- Die E-Mail-Adresse mit RegEx validieren und gar nicht erlauben, auf anmelden zu klicken, wenn keine valide Mail eingegeben wurde

Aber das machen wir erstmal nicht. Für den unwahrscheinlichen Fall, dass noch Zeit übrig ist... dann vielleicht.

So ist erstmal gut.

2024-06-21 16:21 UTC, julius-boettger commented on src/routes/login/+page.svelte
> +    let passwordIndicator = indicatorStatus.none; // Will get value "input-error" or "input-warning" according to status of backend fetch and validators
```suggestion
    // Will get value "input-error" or "input-warning" according to status of backend fetch and validators
    let emailIndicator = indicatorStatus.none;
    let passwordIndicator = indicatorStatus.none;
```
Das reicht einmal

2024-06-21 16:21 UTC, julius-boettger commented on src/routes/user/+page.js
> +    return users[0]; //only for testing
```suggestion
    return users[0]; // Only for testing
```

2024-06-21 17:48 UTC, Janniix commented
Ein "Passwort anzeigen Icon" sollte eigentlich im Passwordfeld mit angezeigt werden, maybe bekomme ich noch hin das weiß zu bekommen, dann sieht man das auch besser

2024-06-21 17:49 UTC, Janniix commented
nvm du hast recht, wenn man einmal raus und wieder rein klickt ist der weg tf

2024-06-22 08:01 UTC, julius-boettger approved these changes

2024-06-22 08:01 UTC, merged