us-88 Registrierungsseite bauen mit Tailwind Forms
solid-stack-solutions/voycar-frontend pull request #16
Opened 2024-06-25 20:10 UTC by NilsPvR

[User story 88](https://tree.taiga.io/project/julius-boettger-voycar/us/88)

Es gibt jetzt eine Registrierungsseite mit einem mehrere Schritte form. Es gibt noch keine backend logik Anbindung in diesem branch.
Da es noch keine backend Logik gibt, werden für die Abos Platzhalter verwendet

![grafik](https://github.com/solid-stack-solutions/voycar-frontend/assets/58894308/2cf1b29d-9374-41f3-8606-85fef7e475e9)
![grafik](https://github.com/solid-stack-solutions/voycar-frontend/assets/58894308/8a8e32f2-4288-48d7-8ecf-56da44f24027)
![grafik](https://github.com/solid-stack-solutions/voycar-frontend/assets/58894308/cd174c33-db99-4821-88b4-6ed2d5cbcbbd)

2024-06-26 19:29 UTC, julius-boettger requested changes
Der Date Picker fürs Geburtsdatum ist Default vom Browser, oder? Wär schon schöner den selbst stylen zu können, dann würde er auch in allen Browsern gleich aussehen. Aber kann man auch noch später, ist probably etwas aufwendiger.

Bitte auch noch überall "😉" durch ";)" ersetzen, wie gerade auf Signal beschlossen.

Noch eine kleine Idee, fänd ich super cool, vielleicht hast du ja Bock das zu machen, aber muss auch nicht: Die drei Tarife leicht unterschiedlich dargestellen. Den teuersten in der Mitte, mit farbigem Hintergrund oder irgendwas anderem, was Aufmerksamkeit auf sich zieht. Den mittleren Tarif links, bisschen kleiner und etwas weniger auffällig. Den günstigsten Tarif rechts, am kleinsten und am wenigsten auffällig. Was "groß/klein" heißt, ist dir überlassen, vielleicht nur die Größe des Preises und nicht des ganzen Tarif-Divs verändern oder so.

2024-06-26 19:29 UTC, julius-boettger commented on src/routes/register/+page.svelte
> +    let registerSteps = ["User", "Member", "Plan"];
Könnte das auch `const` sein?

2024-06-26 19:29 UTC, julius-boettger commented on src/routes/register/components/backButton.svelte
> +    }}
```suggestion
    on:click={() => currentStep--}
```

2024-06-26 19:29 UTC, julius-boettger commented on src/routes/register/components/planForm.svelte
> +                {#each temp as _}
Warum `_`?

2024-06-26 19:29 UTC, julius-boettger commented on src/routes/register/components/planForm.svelte
> +                            Alles nötige zum Durchstarten.
```suggestion
                            Alles Nötige zum Durchstarten.
```

2024-06-26 19:36 UTC, NilsPvR commented on src/routes/register/components/planForm.svelte
> +                {#each temp as _}
Weil es temporär sein soll und eigentlich keine wirkliche Bedeutung hat. Kann ich aber auch zu `plan` umbenennen.

2024-06-26 19:51 UTC, julius-boettger commented on src/routes/register/components/planForm.svelte
> +                {#each temp as _}
Ja, das fänd ich besser.

2024-06-26 20:14 UTC, NilsPvR commented on src/routes/register/components/planForm.svelte
> +                {#each temp as _}
e721ae1

2024-06-26 20:14 UTC, NilsPvR commented on src/routes/register/+page.svelte
> +    let registerSteps = ["User", "Member", "Plan"];
e721ae1

2024-06-26 20:15 UTC, NilsPvR commented
Bisschen spannenderes Design klingt eig. ganz gut. Ich gucke mal wie aufwendig das ist.

2024-06-27 15:06 UTC, NilsPvR commented
Emoji ist ersetzt (auch in Login). Wie besprochen noch kein Datepicker. Abos Auswahl sieht wie besprochen jetzt so aus:
![grafik](https://github.com/solid-stack-solutions/voycar-frontend/assets/58894308/ea6e0e31-9253-40a7-b05e-ec81ea9094bf)

2024-06-27 15:09 UTC, julius-boettger approved these changes

2024-06-27 15:09 UTC, merged