us-200 Neue Reservierungen anlegen Seite gestalten
solid-stack-solutions/voycar-frontend pull request #27
Opened 2024-06-29 18:28 UTC by Janniix

[User story 200](https://tree.taiga.io/project/julius-boettger-voycar/us/200)

Es können jetzt neue Reservierungen angelegt werden. 
Dabei wird auch geprüft, ob der ausgewählte Zeitraum valid ist und einem werden nur Autos angezeigt die in dem gegeben Zeitraum verfügbar sind.
Das Problem, dass teilweise Content angezeigt wird, wenn man nicht angemeldet ist, wird in [us-216](https://tree.taiga.io/project/julius-boettger-voycar/us/216) adressiert werden.

2024-06-29 19:00 UTC, julius-boettger requested changes
Fehlt noch ein `npm run format`.

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                );
Auch wenn Swagger das nicht so anzeigt, solltest du dem GET /car/available Endpunkt deine `searchParams` auch als JSON Request Body und nicht als `URLSearchParams` übergeben können. Das würde ich vorziehen, weil es eigentlich ein Versehen ist, dass der Endpunkt überhaupt `URLSearchParams` akzeptiert. Dann sollte die lokale Variable aber probably auch nicht merh `searchParams` sondern eher `requestBody` heißen.

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +    });
```suggestion
    onMount(fetchAllStations);
```
Geht das hier auch?

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                <!-- Formpage 1: Selection of station and date of begining and end of reservation -->
```suggestion
                <!-- Formpage 1: Selection of station and date of beginning and end of reservation -->
```

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                                <th> Beginn: </th>
```suggestion
                                <th>Beginn:</th>
```

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                                <th> Ende: </th>
```suggestion
                                <th>Ende:</th>
```

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                                <th> Station: </th>
```suggestion
                                <th>Station:</th>
```

2024-06-29 19:00 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                                <th> Auto: </th>
```suggestion
                                <th>Auto:</th>
```

2024-06-29 19:14 UTC, julius-boettger commented
Es scheint auch noch keinen Check dafür zu geben, wenn Beginn und Ende exakt gleich sind. Also z. B. beides 29.06.2024 21:13 Uhr. Da sollte man auch die Message bekommen "Bitte gib einen validen Zeitraum an", aktuell wird man aber so weitergeleitet als wärs richtig, und dann passiert nichts. Bitte Check dafür einbauen.

2024-06-29 19:19 UTC, julius-boettger commented
Bitte noch einen Check dafür einbauen, dass Beginn und Ende exakt gleich sind. Also z. B. 29.06.2024 21:18 Uhr. Dann sollte auch "Bitte gib einen validen Zeitraum an" angezeigt werden, wirds aktuell nicht, man kommt weiter, aber das Backend gibt Bad Request zurück.

2024-06-29 19:22 UTC, julius-boettger commented
Der Radio-Button um ein Auto auszuwählen geht nicht, wenn man direkt draufklickt. Man kann überall anders hinklicken, aber nicht direkt auf den Radio-Button :joy: Das ist etwas verwirrend.
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/da67c964-220d-45b7-84f6-d67b44f28a28)

2024-06-29 19:25 UTC, julius-boettger commented
Mir fällt auch gerade auf, dass wir an drei verschiedenen Stellen sehr ähnliche Informationen darstellen, aber jedes Mal mit anderem Layout... wäre probably schöner das einheitlich als ausgelagerte Komponente zu haben

Verfügbares Auto auswählen:
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/45e94ae9-607e-4257-bad6-5d5161fa695a)
Reservierung bestätigen:
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/52591e24-20b6-4e59-a74b-098da2479676)
Getätigte Reservierung angucken:
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/3d4406db-3609-461a-a918-bcf882489cea)

2024-06-29 19:30 UTC, julius-boettger commented
Und irgendwas anderes ist noch komisch...
Auf Landing Page:
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/487ddfca-c8fd-48fd-baf6-58fe2a80ecbf)
Auf `/user`:
![image](https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/7be81e8a-d3f5-41a9-b215-1b0a563ae027)

2024-06-29 19:33 UTC, NilsPvR commented
Habe bisher nur getestet und noch nicht den Code angeguckt.

## Probleme
Der Statuscode 400 sollte vermutlich noch abgefangen werden, aktuell wird einfach ein Fehler in die Konsole ausgegeben.
Es sollte abgefangen werden, wenn das Backend nicht erreichbar ist

## Verbesserungsvorschläge (müssen wir nicht umsetzen, ist mir nur aufgefallen)
- Es wäre cool, wenn das Datum gespeichert bleibt, wenn man zum Auto navigiert und dann wieder zurückklickt. (vllt. kann ich nacher noch nen Code Vorschlag dazu machen)
- Ebenfalls das ausgewählte Auto wird nicht gespeichert 
- Es gibt keine Fehlermeldung, wenn man kein Auto auswählt
- Wie auch beim Login wäre es cool, wenn der Reservierung button gesperrt wird, nachdem der gedrückt wurde
- Ladeanimation/Placeholder, wenn Autos geladen werden

2024-06-29 19:36 UTC, NilsPvR commented
> Mir fällt auch gerade auf, dass wir an drei verschiedenen Stellen sehr ähnliche Informationen darstellen, aber jedes Mal mit anderem Layout... wäre probably schöner das einheitlich als ausgelagerte Komponente zu haben

Muss man dann natürlich gucken, wie man das mit dem Radio Button macht. Oder lässt man den dann evtl. weg?

2024-06-29 19:39 UTC, julius-boettger commented
> Muss man dann natürlich gucken, wie man das mit dem Radio Button macht. Oder lässt man den dann evtl. weg?

Eigentlich finde ich den schon gut, ich hoffe mal, es geht auch irgendwie neben der Auto-Info-Komponente noch nen Radio-Button anzuzeigen

2024-06-29 20:40 UTC, NilsPvR requested changes
Aber es geht. Sehr cool 👍 
Ich glaube bezüglich meiner vorherigen Anmerkungen bei Fehlern zum Laden der Daten: Einfach in die catches jeweils ein Toast machen und `formPage` wieder auf 0 setzen.

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +        endIndicator = indicatorStatus.none;
Gleiche Reihenfolge wie oben
```suggestion
        beginIndicator = indicatorStatus.none;
        endIndicator = indicatorStatus.none;
        periodIndicator = false;
        emptyIndicator = false;
```

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +                );
Ja in Bruno geht das zwar, aber die [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#setting_a_body) lässt das nicht zu. Da kommt auch eine Fehlermeldung, wenn man ein GET mit body macht.

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +        console.log("false");
Kann weg?
```suggestion
```

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +        }
Das Auto würde ich unten beim onClick speichern. Hier dann den loop mit `forEach()`
```suggestion
    function checkCarSelected() {
        let checked = false;
        document.getElementsByName("radio-button").forEach(button => {
            if (button.checked) {
                checked = true;
            }
        });

        return checked;
    }
```

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +                                    if (checkAndSaveCarSelected(loadedCars)) {
Hier dann den Methodennamen von oben übernehmen
```suggestion
                                    if (checkCarSelected()) {
```

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +                    bind:this={beginReference}
Gibt es einen Grund hier nicht auch `bind:value{xxx}` zu verwenden? Ebenso bei end input. Dann bräuchte man die `saveSelected` Methode auch nicht mehr

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +            console.log(mybody);
Kann weg?
```suggestion
```

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +                        }
Bitte in eigene Methode auslagern

2024-06-29 20:40 UTC, NilsPvR commented on src/routes/user/data.js
Löscht er einfach die Datei, die noch bei mehreren Sachen importiert wird 😆

2024-06-29 21:34 UTC, Janniix commented on src/routes/user/data.js
Huch stimmt

2024-06-29 21:54 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +                );
also jetzt so lassen wie es dann grad ist?

2024-06-29 21:55 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +    });
yes scheint doch zu funktionieren

2024-06-29 22:01 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +                    bind:this={beginReference}
ich meine das hatte ich versucht und das ging dann irgendwie nicht, aber ich gucke nochmal

2024-06-29 22:03 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +                                <th> Auto: </th>
nur kurz zur Info, die Spaces mache nicht ich, sondern prettier dahin 😂 ich mach das nicht um dich zu ärgern oder so

2024-06-29 22:06 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +        }
und wo/wo speicher ich mir dann das Auto ab? Also woher weiß ich dann welches Auto ausgewählt ist?

2024-06-30 07:48 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                );
Schade, ja dann so lassen wie jetzt, geht laut Nils ja nicht wie ichs wollte

2024-06-30 07:49 UTC, julius-boettger commented on src/routes/new-reservation/+page.svelte
> +                                <th> Auto: </th>
Yes, hab ich mir schon gedacht :)

2024-06-30 09:39 UTC, NilsPvR commented on src/routes/new-reservation/+page.svelte
> +        }
Ahh hab' vergessen die suggestion beim onClick zu machen. Hab das nur lokal erst bei mir getestet 😅

2024-06-30 09:46 UTC, NilsPvR commented on src/lib/util.js
> +}
👍 😂

2024-06-30 11:40 UTC, Janniix commented
> > Muss man dann natürlich gucken, wie man das mit dem Radio Button macht. Oder lässt man den dann evtl. weg?
> 
> Eigentlich finde ich den schon gut, ich hoffe mal, es geht auch irgendwie neben der Auto-Info-Komponente noch nen Radio-Button anzuzeigen

i hate to break it to you, aber der 📻 button wurde entfernt 🦺

2024-06-30 11:54 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +        }
Haben wir zusammen im Call angepasst und wird deshalb nicht mehr gebraucht, merci 🤩🤖

2024-06-30 13:01 UTC, Janniix commented
> Mir fällt auch gerade auf, dass wir an drei verschiedenen Stellen sehr ähnliche Informationen darstellen, aber jedes Mal mit anderem Layout... wäre probably schöner das einheitlich als ausgelagerte Komponente zu haben

Ich habe das jetzt als Komponente ausgelagert für "verfügbares Auto angucken" und "Reservierung angucken" beim Bestätigen würde ich das so lassen, da das da ja nur das Modell drin steht

2024-06-30 13:02 UTC, Janniix commented
> > > Muss man dann natürlich gucken, wie man das mit dem Radio Button macht. Oder lässt man den dann evtl. weg?
> > 
> > 
> > Eigentlich finde ich den schon gut, ich hoffe mal, es geht auch irgendwie neben der Auto-Info-Komponente noch nen Radio-Button anzuzeigen
> 
> i hate to break it to you, aber der 📻 button wurde entfernt 🦺

Aber ich würde sagen, wir haben eine coole Alternative gefunden, die actually sogar kinda besser ist

2024-06-30 13:26 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +                    bind:this={beginReference}
wurde geändert

2024-06-30 13:26 UTC, Janniix commented on src/routes/new-reservation/+page.svelte
> +                        }
wurde ausgelagert

2024-06-30 13:26 UTC, Janniix commented on src/lib/util.js
> +}
🍞

2024-06-30 13:35 UTC, julius-boettger requested changes

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/carDataComponent.svelte
> +            <th> Kennzeichen: </th>
```suggestion
            <th>Kennzeichen:</th>
```

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/carDataComponent.svelte
> +        <th> Marke: </th>
```suggestion
        <th>Marke:</th>
```

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/carDataComponent.svelte
> +        <th> Typ: </th>
```suggestion
        <th>Typ:</th>
```

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/carDataComponent.svelte
> +        <th> Leistung: </th>
```suggestion
        <th>Leistung:</th>
```

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/carDataComponent.svelte
> +        <th> Sitzplätze: </th>
```suggestion
        <th>Sitzplätze:</th>
```

2024-06-30 13:35 UTC, julius-boettger commented on src/routes/reservations/reservation.svelte
> +                >Reservierung Stornieren</button
```suggestion
                >Reservierung stornieren</button
```

2024-06-30 13:41 UTC, julius-boettger approved these changes

2024-06-30 14:03 UTC, julius-boettger requested changes

2024-06-30 14:03 UTC, julius-boettger commented on src/routes/user/+page.svelte
> +            Falls du nicht automatisch weitergeleitet wirst klick auf
```suggestion
            Falls du nicht automatisch weitergeleitet wirst klick
```

2024-06-30 14:03 UTC, julius-boettger commented on src/routes/user/loggedInUser.svelte
> +                    <p>Willst du dein Voyccar-Konto wirklich löschen?</p>
```suggestion
                    <p>Willst du dein Voycar-Konto wirklich löschen?</p>
```

2024-06-30 14:05 UTC, julius-boettger approved these changes

2024-06-30 14:22 UTC, NilsPvR approved these changes
Kleinigkeiten, die ich nur festhalten möchte, falls wir nochmal was anpassen wollen:
- Backend/Frontend Kommunikation macht manchmal Probleme beim Löschen
- Wenn bei Auto Auswahl Backend nicht erreichbar, gibt es keine Fehlermeldung
- Baujahr vom Auto zeigen wird nicht an

 Aber sonst sieht gut aus 👍

2024-06-30 14:23 UTC, merged