us-71 Kontoinformationsseite als Svelte Page gestalten
solid-stack-solutions/voycar-frontend pull request #5
Opened 2024-06-10 18:52 UTC by Janniix

[User story 71](https://tree.taiga.io/project/julius-boettger-voycar/us/71)
Gestaltung der Kontoseite ist so weit durch. Es muss noch ein bisschen Logik und später Backend fetches implementiert werden, aber mit dem Design bin ich erstmal zufrieden. Die Logik ist dann eine andere US wie us-97 oder us-118.
Vieles ist wahrscheinlich noch nicht perfekt, und ein paar Dinge sind grad nur zum Testen ohne Backend so wie sie sind. Die werden dann noch angepasst, sobald die Backend-Interaktion da ist und das Backend auch von ihren Endpunkten auf dem passenden Stand ist. 
Bei Fragen oder Unklarheiten gerne melden, wäre wahrscheinlich zu viel das alles in ein PR-Review zu packen und manches ist vielleicht aus dem Code nicht klar, warum das so gemacht wurde, deshalb lieber persönlich. 🫡 🖖

2024-06-10 20:38 UTC, julius-boettger requested changes
Generell:
- Kommentare im Code bitte alle auf Englisch
- Bitte "ToDo" anstatt "TODO" oder anderen Varianten
- Bitte `npm run format` machen
- Das Frontend sollte komplett auf Deutsch sein, also z. B. "Bearbeiten" und nicht "Edit" auf den Knopf schreiben
- Große auskommentierte Codeblöcke würde ich ungern mergen, bitte entfernen

Bezüglich des Designs der Kontoinformationsseite:
- Da sind mir etwas zu viele Borders. Also z. B. die doppelte Border von den persönlichen Informationen stört mich, ich hätte da gern 0-1 Border.
- Über dem "Kontolöschung beantragen"-Knopf und unter dem "Hallo [Name]" hätte ich gern noch etwas mehr Spacing, das sieht mir sehr eng aus.

Bezüglich der User-Experience (gilt für "persönliche Informationen"- und "Zahlungsinformation"-Tab):
- Wenn man den Edit-Knopf drückt, kommt ja in eine Art "Edit-Modus". Ich finde es allerdings unklar, dass man diesen auch wieder verlässt, wenn man denselben Knopf nochmal drückt. Also den Knopf vielleicht "Bearbeiten beenden" oder so nennen, während man im Edit-Modus ist, damit das klarer ist.
- Ich finde es komisch, dass ich den Edit-Modus verlassen kann, ohne auf "Update" zu klicken. Ich würde erwarten, dass dann entweder meine Changes discarded werden, oder automatisch ein Update ausgeführt wird. Augenscheinlich passiert aktuell nichts...?
    - Falls ein automatisches Update durchgeführt wird, ist dies nicht erkennbar. Könnte man z. B. durch sowas wie einen "Bearbeiten beenden und speichern"-Knopf ersichtlich machen.

2024-06-11 12:24 UTC, Janniix commented
Danke für dein Review, 

die deutschen Kommentare beschreiben Dinge, die später noch geändert werden bzw. geben Hinweise darauf wie die Logik dann aussehen soll. Sie werden obvs nicht im fertigen Programm stehen. Sie helfen aber dabei, solche Art von Kommentare von beschreibenden (also dann auch bleibenden) Kommentaren im Englischen zu unterscheiden.

Warum sollen To-Dos als ToDo geschrieben werden? TODO wird in meinem VS-Code gehighlightet, übersichtlich zusammengefasst und es fällt eher ins Auge als ToDo (maybe müssen wir uns da einheitlich festlegen).

Formatierung werde ich in einem neuen Commit dann anpassen.

Fronend kann ich auch auf Deutsch anpassen.

Die Codeblöcke sind auskommentiert, damit ich/ oder wer auch immer das dann macht, eine Hilfestellung/Ansatz hat, bzw. ich mir das merken wollte, es aber nicht zu dieser US gehört hat. Kann ich meinetwegen entfernen, auch wenn ich die jetzt nicht schlimm finde.

Die Border um die Tabelle kann ich anpassen; Spacing kann auch verändert werden.

Zu den Anmerkungen zur User Experience: Ich fand das starten und beenden des Bearbeiten Modus durch einen Knopf jetzt nicht so unintuitiv, aber ja da kann man sonst noch was ändern. 
In Bezug auf die Update/Discard Logik: Da hatte ich auch erst rumprobiert, aber gemerkt, dass sowas eigentlich nicht in die Gestaltung der Seite gehört, sondern eher in die Logik. Das wird dann also in einer anderen US angepasst.

Ich kann die Punkte teilweise nachvollziehen, aber ich meinte ja auch schon, dass man am besten direkt mit mir reden sollte, damit ich die Unklarheiten/Entscheidungen erläutern kann.

2024-06-11 12:38 UTC, Janniix commented
Hab jetzt erstmal den Großteil umgesetzt, über das Andere können wir ja nochmal reden

2024-06-11 20:24 UTC, julius-boettger commented
(kurze Zusammenfassung, was wir persönlich besprochen haben)

> die deutschen Kommentare beschreiben Dinge, die später noch geändert werden bzw. geben Hinweise darauf wie die Logik dann aussehen soll. Sie werden obvs nicht im fertigen Programm stehen. Sie helfen aber dabei, solche Art von Kommentare von beschreibenden (also dann auch bleibenden) Kommentaren im Englischen zu unterscheiden.

Bitte trotzdem alle Code Kommentare auf Englisch, kann ja noch ein `ToDo` davor.

> Warum sollen To-Dos als ToDo geschrieben werden? TODO wird in meinem VS-Code gehighlightet, übersichtlich zusammengefasst und es fällt eher ins Auge als ToDo (maybe müssen wir uns da einheitlich festlegen).

Weil wir uns im Backend schon auf die Konvention geeinigt haben, es als `ToDo` zu schreiben.

> Die Codeblöcke sind auskommentiert, damit ich/ oder wer auch immer das dann macht, eine Hilfestellung/Ansatz hat, bzw. ich mir das merken wollte, es aber nicht zu dieser US gehört hat. Kann ich meinetwegen entfernen, auch wenn ich die jetzt nicht schlimm finde.

Ja, bitte entfernen.

> Zu den Anmerkungen zur User Experience: [...] Da hatte ich auch erst rumprobiert, aber gemerkt, dass sowas eigentlich nicht in die Gestaltung der Seite gehört, sondern eher in die Logik. Das wird dann also in einer anderen US angepasst.

Klingt sinnvoll, dann kommt das in eine andere US.

2024-06-12 19:02 UTC, julius-boettger requested changes
Bitte in Zukunft mehr darauf achten, ob du Spaces am Anfang/Ende von Kommentaren setzt, damit das überall konsistent bleibt. Dasselbe gilt für Groß-/Kleinschreibung in Kommentaren.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +                    <td>
Hmm ich bin irgendwie immer noch nicht so zufrieden mit dem Design von der "Persönliche Informationen"-Section. Hier ein Vorschlag. (Ist das folgende Git Diff nur bei mir broken?) 

```suggestion
<div class="p-2">
    <table class="">
        {#each userKeys as key, i}
            <!-- Only show rows with information available -->
            {#if userInfo[i] != null}
                <!-- Diplays all the information of the specified user in the url params 
                (doesnt sanitize the data its given; means query data has to be clean) -->
                <tr>
                    <th class="text-end">
                        <span class="mr-5">{key.toLowerCase()}</span>
                    </th>
                    <td class="w-full">
```

Sieht dann so aus:

<image width=400 src="https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/d4999264-b00a-4779-a037-4a2c0fc68c93"/>

For reference, vorher war so:

<image width=400 src="https://github.com/solid-stack-solutions/voycar-frontend/assets/85450899/69463c85-a6e4-455a-b39f-fc81b7b7d2cf"/>

2024-06-12 19:02 UTC, julius-boettger commented on src/lib/util.js
> +//routing strings
```suggestion
// Routing strings
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +    import { TabGroup, Tab, TabAnchor } from "@skeletonlabs/skeleton"; //Menu with Tabs
```suggestion
    import { TabGroup, Tab, TabAnchor } from "@skeletonlabs/skeleton"; // Menu with tabs
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +    // these are skeleton svelte components!
```suggestion
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +            <!--Voycar Logo-->
```suggestion
            <!-- Voycar Logo -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +            <!--UserIcon-->
```suggestion
            <!-- User icon -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/+page.svelte
> +    //Framework imports
```suggestion
    // Framework imports
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/+page.svelte
> +    //Functions
```suggestion
    // Functions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/+page.svelte
> +        //ToDo fetch user id from backend
```suggestion
        // ToDo fetch user id from backend
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/+page.js
> +//Imports
```suggestion
// Imports
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/+page.js
> +//Functions
```suggestion
// Functions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/+page.svelte
> +    //Component imports
```suggestion
    // Component imports
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/+page.svelte
> +    //Export data from parent
```suggestion
    // Export data from parent
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +    import { page } from "$app/stores"; // contains all pages in a store
```suggestion
    import { page } from "$app/stores"; // Contains all pages in a store
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +    import { AppBar } from "@skeletonlabs/skeleton"; // App Bar
```suggestion
    import { AppBar } from "@skeletonlabs/skeleton";
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +        </svg>
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/+layout.svelte
> +            </svg>
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/+page.svelte
> +    <!-- Inject loggend in user svelte component -->
```suggestion
    <!-- Inject logged in user svelte component -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +<!-- Account page for loggend in users -->
```suggestion
<!-- Account page for logged in users -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +    const userInfo = Object.values(data.user); //convert JSON object to iterable List
```suggestion
    // Convert JSON object to iterable array
    const userKeys = Object.keys(data.user); 
    const userInfo = Object.values(data.user);
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +        //Popup settings
```suggestion
        // Popup settings
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +    //Functions
```suggestion
    // Functions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +        //ToDo account deletion logic
```suggestion
        // ToDo account deletion logic
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +        // request to backend
```suggestion
        // Request to backend
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +        goto("/"); //redirect to landing page
```suggestion
        goto("/"); // Redirect to landing page
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/loggedInUser.svelte
> +                <!-- Confirmation Button -->
```suggestion
                <!-- Confirmation button -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +    //Parent data exports
```suggestion
    // Parent data exports
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +    //Definitions
```suggestion
    // Definitions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +        >
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +            >
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +    //Definitions
```suggestion
    // Definitions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +    //ToDo logic for backend fetch
```suggestion
    // ToDo logic for backend fetch
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +                <p>Paypal</p>
```suggestion
                <p>PayPal</p>
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +                <p>Crypto</p>
```suggestion
                <p>Kryptowährung</p>
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +            <!-- ToDo logic for delete button-->
```suggestion
            <!-- ToDo logic for delete button -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +            >
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPaymentData.svelte
> +                >
SVG bitte (wenn möglich) in eigene Datei auslagern.

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPlanData.svelte
> +    //Definitions
```suggestion
    // Definitions
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPlanData.svelte
> +    //ToDo logic for backend fetch
```suggestion
    // ToDo logic for backend fetch
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPlanData.svelte
> +    //ToDo maybe show possible plan and option to change current one
```suggestion
    // ToDo maybe show possible plan and option to change current one
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/[userID]/userPlanData.svelte
> +    <!-- currently placeholder; will be changed when backend fetch possible -->
```suggestion
    <!-- Currently a placeholder; will be changed when backend fetch possible -->
```

2024-06-12 19:02 UTC, julius-boettger commented on src/routes/user/data.js
> +//Test data
```suggestion
// Test data
```

2024-06-12 20:31 UTC, Janniix commented
Vorgeschlagene Änderungen wurden vorgenommen 🫡

2024-06-12 20:35 UTC, julius-boettger requested changes

2024-06-12 20:35 UTC, julius-boettger commented on src/routes/user/[userID]/userData.svelte
> +    <table class="">
```suggestion
    <table>
```

2024-06-12 20:46 UTC, julius-boettger approved these changes

2024-06-12 20:46 UTC, merged