us-118 User Daten Fetch ans Backend
solid-stack-solutions/voycar-frontend pull request #9
Opened 2024-06-20 16:40 UTC by Janniix

[User story 118](https://tree.taiga.io/project/julius-boettger-voycar/us/118)

2024-06-20 20:53 UTC, julius-boettger commented
Ich review das morgen auch noch

2024-06-20 21:08 UTC, NilsPvR requested changes
Das sieht schon sehr nice aus. Vor allem die Placeholder sind schick. 

Ich nehme mal an, du hast noch nicht mit tatsächlichen Backend-Daten testen können?

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +    // Import 🐓
😆 
```suggestion
    // Import 🐦
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +        timeout: 3000, //auto dismiss toast after 3 seconds
```suggestion
        hideDismiss: true, // Hide the dismiss button on toast
        timeout: 3000, // Auto dismiss toast after 3 seconds
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +    const t = {
So ist eig. schöner, auch wenn Skeleton das anders macht.
```suggestion
    const toastSettings = {
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +            toastStore.trigger(t);
Entsprechend zu oben anpassen
```suggestion
            toastStore.trigger(toastSettings);
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +            goto("/"); // redirect user to landing page
```suggestion
            goto("/"); // Redirect user to landing page
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +            > um zur Startseite zurückzukehren!
Je nachdem, ob wir jetzt "Du" oder "Sie" verwenden, muss das noch angepasst werden. 
```suggestion
            Falls Sie nicht automatisch weitergeleitet werden klicken Sie 
            <a href="/" class="text-primary-500 underline">hier</a>
            um zur Startseite zurückzukehren!
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +        <p class="text-center">Fehler: {error}</p>
Bisschen spacing
![grafik](https://github.com/solid-stack-solutions/voycar-frontend/assets/58894308/bb151b31-0a96-4af6-9bf7-8f189c2e5566)

```suggestion
        <p class="text-center pt-2">Fehler: {error}</p>
```

2024-06-20 21:08 UTC, NilsPvR commented on src/routes/user/userPageLoadingPlaceholders.svelte
> +    <div class="placeholder animate-pulse w-60 h-12 absolute right-0 mt-2" />
Habe jetzt schon [US 167](https://tree.taiga.io/project/julius-boettger-voycar/us/167) erstellt, aber würde schonmal stark beeinflussende Klassen vorne hinschreiben.
```suggestion
    <div class="placeholder animate-pulse w-60 h-8 mb-4" />
    <div class="space-y-2">
        {#each { length: 3 } as _}
            <div class="placeholder animate-pulse h-10"></div>
        {/each}
    </div>
    <div class="placeholder animate-pulse absolute w-60 h-12 right-0 mt-2" />
```

2024-06-20 21:53 UTC, NilsPvR requested changes

2024-06-20 21:53 UTC, NilsPvR commented on src/routes/user/+page.svelte
> +    {/if}
Ich hoffe ich verursache jetzt selber keine Konflikte mit doppelten Vorschlägen... aber hier kann man eig. ganz cool das Svelte `await` verwenden (auch wenn meine Implementierung noch nicht die beste ist). 

Wenn akzeptiert, bitte meinen Vorschlag noch kurz testen und maybe reformatten.
```suggestion
    let personalData = new Promise((resolve, reject) => {}); // Set non resolving promise as default

    // Toast settings
    const t = {
        message: "Ihr Nutzerkonto konnte nicht gefunden werden",
        hideDismiss: true, //hide the dismiss button on toast
        timeout: 3000, //auto dismiss toast after 3 seconds
        background: "variant-filled-secondary",
    };

    // Functions
    // Runs as soon as this component is mounted
    onMount(async () => {
        personalData = new Promise(async (resolve, reject) => {
            try {
                // Fetch backend for personal Data with retry policy
                const response = await retryPolicy.execute(() =>
                    fetch(urls.get.memberPersonalData),
                );
                if (response.ok) {
                    personalData = resolve(await response.json());
                    loading = false;
                } else {
                    throw new Error("Error while fetching data");
                }
            } catch (err) {
                toastStore.trigger(t);
                goto("/"); // redirect user to landing page
                reject(err); // Rethrow so Svelte can handle it
            }
        });

    });
</script>

<!-- Page Content -->
<div>
    {#await personalData}
        <!-- Display placeholders while loading data -->
        <UserPageLoadingPlaceholders />
    {:then personalData}
        <!-- Display on success -->
        <LoggedInUser {personalData}></LoggedInUser>
    {:catch error}
        <!-- Display on error -->
        <p class="text-center h3">
            Ihr Nutzerkonto konnte nicht gefunden werden. Sie werden auf die
            Startseite zurückgeleitet!
        </p>
        <p class="text-center h3">
            Falls sie nicht automatisch weitergeleitet werden klicken sie <a
                href="/"
                class="text-primary-500 underline">hier</a
            > um zur Startseite zurückzukehren!
        </p>
        <p class="text-center">Fehler: {error.message}</p>
    {/await}
```

2024-06-20 22:07 UTC, Janniix commented on src/routes/user/+page.svelte
> +    {/if}
Klingt sehr cool, baue ich mal ein und probiere das aus. Klingt sinnvoll

2024-06-21 06:18 UTC, julius-boettger approved these changes
Nils' Anmerkungen erscheinen mir sinnvoll.

Bitte nochmal `main` auf diese Branch mergen und `npm run format` machen, es gibt Konflikte weil ich #11 zuerst gemerged habe.

2024-06-21 06:18 UTC, julius-boettger commented on src/lib/util.js
>  // helper functions that can easily be imported anywhere go here
```suggestion
// Helper functions that can easily be imported anywhere go here
```

2024-06-21 10:27 UTC, NilsPvR approved these changes

2024-06-21 10:30 UTC, merged